version: '3.8'

services:
 # app:
 #   build:
 #     context: .
 #     dockerfile: Dockerfile
 #   container_name: cp-app
 #   ports:
 #     - '3000:3000'
 #   environment:
 #     DATABASE_URL: "postgresql://postgres:password@db:5432/cp"
 #   depends_on:
 #     - db
 #   volumes:
 #     - .:/app
 #     - /app/node_modules
 #     - /app/.next
 #   command: npm run start

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: